### ISSUE TITLE
Why not use Tailscale?

### ISSUE THREAD

**Issue by juev** [ValdikSS/nat-traversal-github-actions-openvpn-wireguard#1]
Thank you for this work! It's incredible.

Maybe I don't understand something, we can use this servers for connecting to Github Actions servers  by ssh?

Why just not use Tailscale action for it? Tailscale provide ssh server and you not needed commit your public keys. 

Sorry for stupid questions. :(

**Comment by ValdikSS** [comment]
This is an example of NAT traversal, describing precise steps on how to do that.
The example could be used to understand how to implement NAT traversal in your application, or how could it be added to any UDP application like OpenVPN or WireGuard, which do not support NAT traversal out of the box.

If you only need to setup a VPN for peers behind NAT, then sure, you'd better use applications which already have NAT traversal in them.
